<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="4CV65290DX" ignored="0" name="社区" tests="1" failures="1" timestamp="23 五月 2017 09:06:22 GMT" time="17.785" errors="0">
  <testcase name="testMyInfo" time="6.826" classname="test.MyinfoPageTest">
    <failure type="java.lang.AssertionError" message="检查点不通过 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: 检查点不通过 expected [true] but found [false]
	at test.MyinfoPageTest.testMyInfo(MyinfoPageTest.java:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testMyInfo -->
</testsuite> <!-- 社区 -->
